addonsrepo/views/pages.py
# SPDX-FileCopyrightText: 2024-present Raoul Snyman <raoul@snyman.info>
#
# SPDX-License-Identifier: MIT
from quart import Blueprint, abort, render_template
from sqlalchemy.sql.expression import select

from addonsrepo.db import Session
from addonsrepo.models import Page, PageStatus


pages = Blueprint('pages', __name__, url_prefix='/pages')


@pages.route('/<path:slug>', methods=['GET'])
async def view(slug: str):
    with Session() as session:
        page = session.scalars(select(Page).where(Page.slug == slug, Page.status == PageStatus.Published)).first()
        if not page:
            abort(404)
    return await render_template('pages/view.html', page=page)

addonsrepo/views/user.py
from secrets import token_urlsafe

from quart import Blueprint, render_template, request, redirect, url_for, flash, session
from quart_auth import AuthUser, login_user, logout_user
from sqlalchemy.sql.expression import select, or_

from addonsrepo.bcrypt import bcrypt
from addonsrepo.db import Session
from addonsrepo.mail import send_email
from addonsrepo.models import User, UserStatus


user = Blueprint('user', __name__)


@user.route('/login', methods=['GET'])
async def login():
    return await render_template('user/login.html')


@user.route('/login', methods=['POST'])
async def login_post():
    form = await request.form
    with Session() as session:
        user = session.scalars(select(User).where(User.email == form.get('email'),
                                                  User.status == UserStatus.Active)).first()
    if user and bcrypt.check_password_hash(user.password, form.get('password')):
        login_user(AuthUser(user.id), form.get('remember', 'false') == 'true')
        await flash('Logged in successfully', 'success')
        return redirect(url_for('addons.index'))
    else:
        await flash('Email or password are incorrect', 'danger')
        return redirect(url_for('user.login'))


@user.route('/register', methods=['GET'])
async def register():
    username = session.pop('username', None)
    email = session.pop('email', None)
    return await render_template('user/register.html', username=username, email=email)


@user.route('/register', methods=['POST'])
async def register_post():
    form = await request.form
    if not form.get('username') or not form.get('email') or not form.get('password'):
        session['username'] = form.get('username')
        session['email'] = form.get('email')
        await flash('Please fill all fields', 'warning')
        return redirect(url_for('user.register'))
    if form.get('agree-tos', 'false') != 'true':
        session['username'] = form.get('username')
        session['email'] = form.get('email')
        await flash('You need to agree to the terms of service', 'warning')
        return redirect(url_for('user.register'))
    with Session() as sess:
        existing_user = sess.scalars(select(User).where(or_(User.username == form['username'],
                                                            User.email == form['email']))).first()
        if existing_user:
            session['username'] = form.get('username')
            session['email'] = form.get('email')
            await flash('User with these details already exists', 'danger')
            return redirect(url_for('user.register'))
        else:
            user = User(username=form['username'], email=form['email'],
                        password=bcrypt.generate_password_hash(form['password']).decode('utf8'),
                        activation_code=token_urlsafe(48))
            sess.add(user)
            sess.commit()
            sess.refresh(user)
            await send_email(user.email, '[OpenLP Addons] Activate Your Account', 'mail/activation.txt', user=user)
            await flash('Account created! Check your email for an activation link, including your junk folder',
                        'success')
            return redirect(url_for('addons.index'))
    return await render_template('user/register.html')


@user.route('/activate/<code>', methods=['GET'])
async def activate(code: str):
    """Activate a user's account"""
    with Session() as sess:
        user = sess.scalars(select(User).where(User.activation_code == code)).first()
        if not user:
            await flash('Cannot find user with this activation code, your account may already be activated', 'warning')
        else:
            user.status = UserStatus.Active
            user.activation_code = None
            sess.add(user)
            sess.commit()
            await flash('Your account has been activated, please log in', 'success')
    return redirect(url_for('addons.index'))


@user.route('/logout')
async def logout():
    logout_user()
    await flash('You have been logged out', 'success')
    return redirect(url_for('addons.index'))

addonsrepo/templates/user/login.html
{% extends 'master.html' %}
{% block pagetitle %}Sign in - OpenLP Addons{% endblock %}
{% block extrastyles %}
    <link href="{{ url_for('static', filename='css/login.css') }}" rel="stylesheet">
{% endblock extrastyles %}
{% block bodyclasses %}d-flex align-items-center py-4 bg-body-tertiary{% endblock %}
{% block layout %}
</main>
<main class="form-login w-100 m-auto">
  <form action="{{ url_for('user.login_post') }}" method="post">
    <img class="mb-4" src="{{ url_for('static', filename='icons/openlp-logo.svg') }}" alt="" width="72" height="57">
    <h1 class="h3 mb-3 fw-normal">Please log in</h1>
    {% for category, message in get_flashed_messages(with_categories=True) %}
    <div class="alert alert-{{ category }}" role="alert">
      {{ message }}
    </div>
    {% endfor %}
    <div class="form-floating first">
      <input type="email" class="form-control" id="email" name="email" placeholder="name@example.com">
      <label for="email">Email address</label>
    </div>
    <div class="form-floating last">
      <input type="password" class="form-control" id="password" name="password" placeholder="Password">
      <label for="password">Password</label>
    </div>

    <div class="form-check text-start my-3">
      <input class="form-check-input" type="checkbox" value="true" id="remember" name="remember">
      <label class="form-check-label" for="remember">
        Remember me
      </label>
    </div>
    <button class="btn btn-primary w-100 py-2 mb-1" type="submit">Sign in</button>
    <a class="btn btn-secondary w-100 py-2 mt-1" href="{{ url_for('addons.index') }}"><i class="bi bi-arrow-left"></i> Back to addons</a>
    <p class="mt-3 mb-3 text-body-secondary">Don't have an account? <a href="{{ url_for('user.register') }}">Register now</a></p>
  </form>
</main>
{% endblock layout %}

addonsrepo/templates/user/register.html
{% extends 'master.html' %}
{% block pagetitle %}Register - OpenLP Addons{% endblock %}
{% block extrastyles %}
    <link href="{{ url_for('static', filename='css/login.css') }}" rel="stylesheet">
{% endblock extrastyles %}
{% block bodyclasses %}d-flex align-items-center py-4 bg-body-tertiary{% endblock %}
{% block layout %}
</main>
<main class="form-login w-100 m-auto">
  <form action="{{ url_for('user.register_post') }}" method="post">
    <img class="mb-4" src="{{ url_for('static', filename='icons/openlp-logo.svg') }}" alt="" width="72" height="57">
    <h1 class="h3 mb-3 fw-normal">Register an account</h1>
    {% for category, message in get_flashed_messages(with_categories=True) %}
    <div class="alert alert-{{ category }}" role="alert">
      {{ message }}
    </div>
    {% endfor %}
    <div class="form-floating first">
      <input type="text" class="form-control" id="username" name="username" placeholder="nickname"{% if username %} value="{{ username }}"{% endif %}>
      <label for="username">Username</label>
    </div>
    <div class="form-floating middle">
      <input type="email" class="form-control" id="email" name="email" placeholder="name@example.com"{% if email %} value="{{ email }}"{% endif %}>
      <label for="email">Email address</label>
    </div>
    <div class="form-floating last">
      <input type="password" class="form-control" id="password" name="password" placeholder="Password">
      <label for="password">Password</label>
    </div>

    <div class="form-check text-start my-3">
      <input class="form-check-input" type="checkbox" value="true" id="agree-tos" name="agree-tos">
      <label class="form-check-label" for="agree-tos">
        I agree to the <a href="{{ url_for('pages.view', slug='terms-of-service') }}">Terms of Service</a>
      </label>
    </div>
    <button class="btn btn-primary w-100 py-2 mb-1" type="submit">Register</button>
    <a class="btn btn-secondary w-100 py-2 mt-1" href="{{ url_for('addons.index') }}"><i class="bi bi-arrow-left"></i> Back to addons</a>
    <p class="mt-3 mb-3 text-body-secondary">Already have an account? <a href="{{ url_for('user.login') }}">Log in</a></p>
  </form>
</main>
{% endblock layout %}