addonsrepo/views/addons.py
import os
from uuid import UUID

from quart import Blueprint, abort, render_template, request, redirect, url_for, session, flash, send_from_directory
from quart_auth import current_user, login_required
from sqlalchemy.sql.expression import select

from addonsrepo.db import Session
from addonsrepo.models import Addon, AddonStatus, AddonType, AddonVersion, PluginProperties, ThemeProperties, User
from addonsrepo.settings import settings
from addonsrepo.utils import paginate, make_basenames


addons = Blueprint('addons', __name__)


@addons.route('/', methods=['GET'])
@addons.route('/<addon_type>', methods=['GET'])
@addons.route('/<addon_type>/<ordering>', methods=['GET'])
async def index(addon_type: str | None = None, ordering: str | None = None):
    page, offset, limit = await paginate(request)
    with Session() as session:
        query = select(Addon).where(Addon.status == AddonStatus.Approved)
        if addon_type and addon_type.endswith('s'):
            addon_type = addon_type[:-1]
        if addon_type not in [str(item) for item in AddonType]:
            addon_type = None
        if addon_type:
            query = query.where(Addon.addon_type == addon_type)
        if ordering:
            if ordering.lower() == 'rating':
                query = query.order_by(Addon.rating.desc())
                page_title = 'Highest rated'
        else:
            page_title = 'Latest'
            query = query.order_by(Addon.created)
        addons = session.scalars(query.order_by(Addon.created).offset(offset).limit(limit)).all()
    return await render_template('addons/index.html', page_title=page_title, type_=addon_type, addons=addons)


@addons.route('/upload/<addon_type>', methods=['GET'])
@login_required
async def upload(addon_type: str):
    if addon_type not in ['theme', 'plugin']:
        return redirect(url_for('addons.index'))
    return await render_template('addons/upload.html', addon_type=addon_type)


@addons.route('/upload/<addon_type>', methods=['POST'])
@login_required
async def upload_post(addon_type: str):
    if addon_type not in ['theme', 'plugin']:
        return redirect(url_for('addons.index'))
    form = await request.form
    files = await request.files
    if os.path.splitext(files['upload'].filename)[-1] not in ['.otz', '.zip']:
        for key, value in form.items():
            session[key] = value
        await flash(f'Invalid file type for your {addon_type}', 'warning')
        return redirect(url_for('addons.upload', addon_type=addon_type))
    with Session() as sess:
        user = sess.scalars(select(User).where(User.id == current_user.auth_id)).first()
        addon = Addon(user=user, title=form['title'], description=form['description'], addon_type=addon_type,
                      status=AddonStatus.Unreviewed, current_version=AddonVersion(version=form['version']))
        if addon_type == AddonType.Theme:
            addon.theme_properties = ThemeProperties(is_copyright_free=form.get('is_copyright_free') == 'true')
        elif addon_type == AddonType.Plugin:
            addon.plugin_properties = PluginProperties(license=form['license'])
        sess.add(addon)
        sess.commit()
        sess.refresh(addon)
        thumbnail_path, file_path = await make_basenames(addon)
        thumbnail_path += os.path.splitext(files['thumbnail'].filename)[-1]
        file_path += os.path.splitext(files['upload'].filename)[-1]
        addon.thumbnail_path = thumbnail_path
        addon.current_version.file_path = file_path
        addon.current_version.addon_id = addon.id
        sess.commit()
        sess.refresh(addon)
    os.makedirs(f'{settings.uploads_folder}/' + os.path.dirname(thumbnail_path), exist_ok=True)
    os.makedirs(f'{settings.uploads_folder}/' + os.path.dirname(file_path), exist_ok=True)
    await files['thumbnail'].save(f'{settings.uploads_folder}/{thumbnail_path}')
    await files['upload'].save(f'{settings.uploads_folder}/{file_path}')
    await flash(f'Your {addon_type} has been submitted for review', 'success')
    return redirect(url_for('addons.index'))


@addons.route('/addon/<addon_id>', methods=['GET'])
async def view(addon_id: str):
    """View an addon"""
    with Session() as session:
        addon = session.scalars(select(Addon).where(Addon.id == UUID(addon_id),
                                                    Addon.status == AddonStatus.Approved)).first()
        if not addon:
            abort(404)
    return await render_template('addons/view.html', addon=addon)


@addons.route('/thumbnail/<path:path>', methods=['GET'])
async def thumbnail(path: str):
    """View an addon"""
    addon_id, path = path.split('/', 1)
    with Session() as session:
        addon = session.scalars(select(Addon).where(Addon.id == UUID(addon_id))).first()
        if not addon:
            abort(404)
    return await send_from_directory(f'{settings.uploads_folder}/{addon_id}', path)


@addons.route('/download/<path:path>', methods=['GET'])
async def download(path: str):
    """View an addon"""
    addon_id, version, path = path.split('/', 2)
    with Session() as session:
        addon = session.scalars(select(Addon).where(Addon.id == UUID(addon_id))).first()
        if not addon:
            abort(404)
    return await send_from_directory(f'{settings.uploads_folder}/{addon_id}/{version}', path)

addonsrepo/views/admin.py
# SPDX-FileCopyrightText: 2024-present OpenLP developers
#
# SPDX-License-Identifier: MIT
from zipfile import ZipFile
from uuid import UUID

from quart import Blueprint, abort, flash, render_template, request, redirect, url_for
from quart_auth import login_required
from sqlalchemy.sql.expression import select, func

from addonsrepo.db import Session
from addonsrepo.models import Addon, AddonStatus, AddonType, User, UserStatus, Page, PageStatus
from addonsrepo.settings import settings
from addonsrepo.utils import paginate, admin_required, moderator_required, title2slug


admin = Blueprint('admin', __name__, url_prefix='/admin')


@admin.route('', methods=['GET'])
@login_required
@moderator_required
async def index():
    with Session() as sess:
        total_addons = sess.scalars(select(func.count(Addon.id))).first()
        total_themes = sess.scalars(select(func.count(Addon.id)).where(Addon.addon_type == AddonType.Theme)).first()
        total_plugins = sess.scalars(select(func.count(Addon.id)).where(Addon.addon_type == AddonType.Plugin)).first()
        unreviewed = sess.scalars(select(func.count(Addon.id)).where(Addon.status == AddonStatus.Unreviewed)).first()
    return await render_template('admin/index.html', total_addons=total_addons, total_themes=total_themes,
                                 total_plugins=total_plugins, unreviewed=unreviewed)


@admin.route('/review', methods=['GET'])
@login_required
@moderator_required
async def review():
    page, offset, limit = await paginate(request, per_page=25)
    # Already awaited above, no need now
    addon_type = request.args.get('type', None)
    with Session() as session:
        query = select(Addon).where(Addon.status == AddonStatus.Unreviewed)
        if addon_type and addon_type.endswith('s'):
            addon_type = addon_type[:-1]
        if addon_type not in [str(item) for item in AddonType]:
            addon_type = None
        if addon_type:
            query = query.where(Addon.addon_type == addon_type)
        addons = session.scalars(query.order_by(Addon.created).offset(offset).limit(limit)).all()
        addon_count = session.scalars(select(func.count(Addon.id)).where(query.whereclause)).first()
        page_total = (addon_count // limit) + (1 if addon_count % limit >= 1 else 0)
    return await render_template('admin/review.html', addons=addons, addon_type=addon_type, page=page, offset=offset,
                                 page_total=page_total)


@admin.route('/review/<addon_id>', methods=['GET'])
@login_required
@moderator_required
async def review_addon(addon_id: str):
    """View an addon for approval or denial"""
    with Session() as sess:
        addon = sess.scalars(select(Addon).where(Addon.id == UUID(addon_id))).first()
        if not addon:
            await flash('That addon does not exist', 'danger')
            return redirect(url_for('admin.review'))
        with ZipFile(f'{settings.uploads_folder}/{addon.current_version.file_path}', 'r') as zipf:
            file_list = zipf.namelist()
        thumbnail_path = addon.thumbnail_path.replace(f'{addon.id}/', '')
    return await render_template('admin/review_addon.html', addon=addon, thumbnail_path=thumbnail_path,
                                 file_list=file_list)


@admin.route('/review/<addon_id>', methods=['POST'])
@login_required
@moderator_required
async def review_addon_post(addon_id: str):
    """Approve or deny an addon"""
    with Session() as sess:
        addon = sess.scalars(select(Addon).where(Addon.id == UUID(addon_id))).first()
        if not addon:
            await flash('That addon does not exist', 'danger')
            return redirect(url_for('admin.review'))
        form = await request.form
        if form.get('action') == 'approved':
            addon.status = AddonStatus.Approved
        elif form.get('action') == 'denied':
            addon.status = AddonStatus.Denied
        sess.add(addon)
        sess.commit()
    await flash(f'Addon successfully {form["action"]}', 'success')
    return redirect(url_for('admin.review'))


@admin.route('/users', methods=['GET'])
@login_required
@admin_required
async def users():
    page, offset, limit = await paginate(request, per_page=25)
    with Session() as session:
        users = session.scalars(select(User).order_by(User.username).offset(offset).limit(limit)).all()
        user_count = session.scalars(select(func.count(User.id))).first()
        page_total = (user_count // limit) + (1 if user_count % limit >= 1 else 0)
    return await render_template('admin/users.html', users=users, page=page, offset=offset, page_total=page_total)


@admin.route('/users/edit/<int:user_id>', methods=['GET'])
@login_required
@admin_required
async def edit_user(user_id: int):
    """Edit an existing user"""
    with Session() as session:
        user = session.scalars(select(User).where(User.id == user_id)).first()
    return await render_template('admin/edit_user.html', user=user, user_statuses=UserStatus)


@admin.route('/users/save/<int:user_id>', methods=['POST'])
@login_required
@admin_required
async def save_user(user_id: int | None = None):
    """Save the user"""
    form = await request.form
    with Session() as session:
        if user_id:
            user = session.scalars(select(User).where(User.id == user_id)).first()
            if not user:
                abort(404)
            user.username = form['username']
            user.email = form['email']
            # if form['password']:
            #     user.password = bcrypt.generate_password_hash(form['password'])
            user.status = form['status']
            user.is_admin = form.get('is_admin', 'false') == 'true'
            user.is_moderator = form.get('is_moderator', 'false') == 'true'
        else:
            user = Page(title=form['title'], slug=form['slug'] or title2slug(form['title']), content=form['content'],
                        status=form['status'])
        session.add(user)
        session.commit()
    await flash('Page saved', 'success')
    return redirect(url_for('admin.users'))


@admin.route('/pages', methods=['GET'])
@login_required
@admin_required
async def pages():
    page, offset, limit = await paginate(request, per_page=25)
    with Session() as session:
        pages = session.scalars(select(Page).order_by(Page.slug).offset(offset).limit(limit)).all()
        page_count = session.scalars(select(func.count(Page.id))).first()
        page_total = (page_count // limit) + (1 if page_count % limit >= 1 else 0)
    return await render_template('admin/pages.html', pages=pages, page=page, offset=offset, page_total=page_total)


@admin.route('/pages/new', methods=['GET'])
@login_required
@admin_required
async def new_page():
    """Add a new page"""
    return await render_template('admin/edit_page.html', page=None, page_statuses=PageStatus)


@admin.route('/pages/edit/<int:page_id>', methods=['GET'])
@login_required
@admin_required
async def edit_page(page_id: int):
    """Edit an existing page"""
    with Session() as session:
        page = session.scalars(select(Page).where(Page.id == page_id)).first()
    return await render_template('admin/edit_page.html', page=page, page_statuses=PageStatus)


@admin.route('/pages/save', methods=['POST'])
@admin.route('/pages/save/<int:page_id>', methods=['POST'])
@login_required
@admin_required
async def save_page(page_id: int | None = None):
    """Save the page"""
    form = await request.form
    with Session() as session:
        if page_id:
            page = session.scalars(select(Page).where(Page.id == page_id)).first()
            if not page:
                abort(404)
            page.title = form['title']
            page.slug = form['slug'] or title2slug(form['title'])
            page.content = form['content']
            page.status = form['status']
        else:
            page = Page(title=form['title'], slug=form['slug'] or title2slug(form['title']), content=form['content'],
                        status=form['status'])
        session.add(page)
        session.commit()
    await flash('Page saved', 'success')
    return redirect(url_for('admin.pages'))

addonsrepo/views/user.py
from secrets import token_urlsafe

from quart import Blueprint, render_template, request, redirect, url_for, flash, session
from quart_auth import AuthUser, login_user, logout_user
from sqlalchemy.sql.expression import select, or_

from addonsrepo.bcrypt import bcrypt
from addonsrepo.db import Session
from addonsrepo.mail import send_email
from addonsrepo.models import User, UserStatus


user = Blueprint('user', __name__)


@user.route('/login', methods=['GET'])
async def login():
    return await render_template('user/login.html')


@user.route('/login', methods=['POST'])
async def login_post():
    form = await request.form
    with Session() as session:
        user = session.scalars(select(User).where(User.email == form.get('email'),
                                                  User.status == UserStatus.Active)).first()
    if user and bcrypt.check_password_hash(user.password, form.get('password')):
        login_user(AuthUser(user.id), form.get('remember', 'false') == 'true')
        await flash('Logged in successfully', 'success')
        return redirect(url_for('addons.index'))
    else:
        await flash('Email or password are incorrect', 'danger')
        return redirect(url_for('user.login'))


@user.route('/register', methods=['GET'])
async def register():
    username = session.pop('username', None)
    email = session.pop('email', None)
    return await render_template('user/register.html', username=username, email=email)


@user.route('/register', methods=['POST'])
async def register_post():
    form = await request.form
    if not form.get('username') or not form.get('email') or not form.get('password'):
        session['username'] = form.get('username')
        session['email'] = form.get('email')
        await flash('Please fill all fields', 'warning')
        return redirect(url_for('user.register'))
    if form.get('agree-tos', 'false') != 'true':
        session['username'] = form.get('username')
        session['email'] = form.get('email')
        await flash('You need to agree to the terms of service', 'warning')
        return redirect(url_for('user.register'))
    with Session() as sess:
        existing_user = sess.scalars(select(User).where(or_(User.username == form['username'],
                                                            User.email == form['email']))).first()
        if existing_user:
            session['username'] = form.get('username')
            session['email'] = form.get('email')
            await flash('User with these details already exists', 'danger')
            return redirect(url_for('user.register'))
        else:
            user = User(username=form['username'], email=form['email'],
                        password=bcrypt.generate_password_hash(form['password']).decode('utf8'),
                        activation_code=token_urlsafe(48))
            sess.add(user)
            sess.commit()
            sess.refresh(user)
            await send_email(user.email, '[OpenLP Addons] Activate Your Account', 'mail/activation.txt', user=user)
            await flash('Account created! Check your email for an activation link, including your junk folder',
                        'success')
            return redirect(url_for('addons.index'))
    return await render_template('user/register.html')


@user.route('/activate/<code>', methods=['GET'])
async def activate(code: str):
    """Activate a user's account"""
    with Session() as sess:
        user = sess.scalars(select(User).where(User.activation_code == code)).first()
        if not user:
            await flash('Cannot find user with this activation code, your account may already be activated', 'warning')
        else:
            user.status = UserStatus.Active
            user.activation_code = None
            sess.add(user)
            sess.commit()
            await flash('Your account has been activated, please log in', 'success')
    return redirect(url_for('addons.index'))


@user.route('/logout')
async def logout():
    logout_user()
    await flash('You have been logged out', 'success')
    return redirect(url_for('addons.index'))

addonsrepo/templates/addons/index.html
{% extends 'addons/master.html' %}
{% block bodyclasses %}no-nav-padding{% endblock %}
{% block mainclasses %}bg-tertiary-subtle{% endblock %}
{% block main %}
  <section class="py-5 mb-5 text-bg-secondary page-{% if type_ %}{{ type_ }}s{% else %}latest{% endif %}">
    <div class="container">
      <h2>{{ page_title }} {% if type_ %}{{ type_ }}s{% else %}themes and plugins{% endif %}</h2>
    </div>
  </section>
  <div class="container">
    {% for category, message in get_flashed_messages(with_categories=True) %}
    <div class="alert alert-{{ category }} alert-dismissible fade show" role="alert">
      {{ message }}
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
    {% endfor %}
    <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
      {% for addon in addons %}
      <div class="col">
        <div class="card shadow-sm h-100">
          <div class="addon-type text-white px-2 py-1">{{ addon.addon_type | title }}</div>
          {% if addon.thumbnail_path %}
          <img src="{{ url_for('addons.thumbnail', path=addon.thumbnail_path) }}" class="card-img-top" alt="{{ addon.title }}">
          {% else %}
          <svg class="bd-placeholder-img card-img-top" width="100%" height="225" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: Thumbnail" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#55595c"/><text x="50%" y="50%" fill="#eceeef" dy=".3em">{{ addon.title }}</text></svg>
          {% endif %}
          <div class="card-body">
            <h5 class="card-title">{{ addon.title }}</h5>
            <h6 class="card-subtitle mb-2 text-body-secondary">by {{ addon.user.username }}</h6>
            <p class="card-text">{{ addon.description }}</p>
          </div>
          <div class="card-footer d-flex justify-content-between align-items-center">
            <small class="text-body-secondary">Version {{ addon.current_version.version }}, updated {{ addon.updated.strftime('%d %b %Y') }}</small>
            <a href="{{ url_for('addons.download', path=addon.current_version.file_path) }}" class="btn btn-sm btn-outline-primary">Download</a>
          </div>
        </div>
      </div>
      {% endfor %}
    </div>
  </div>
{% endblock main %}

addonsrepo/templates/addons/master.html
{% extends 'master.html' %}
{% block layout %}
<nav class="navbar navbar-expand-lg fixed-top bg-secondary-subtle">
  <div class="container">
    <a href="/" class="navbar-brand">
      <img src="{{ url_for('static', filename='icons/openlp-logo.svg') }}" alt="Logo" width="30" class="d-inline-block align-text-top">
      OpenLP Addons
    </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#nav-menu" aria-controls="nav-menu" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="nav-menu">
      <ul class="navbar-nav me-auto">
        <li class="nav-item"><a href="{{ url_for('addons.index', addon_type='themes') }}" class="nav-link">Themes</a></li>
        <li class="nav-item"><a href="{{ url_for('addons.index', addon_type='plugins') }}" class="nav-link">Plugins</a></li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Upload
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="{{ url_for('addons.upload', addon_type='theme') }}">Theme</a></li>
            <li><a class="dropdown-item" href="{{ url_for('addons.upload', addon_type='plugin') }}">Plugin</a></li>
          </ul>
        </li>
      </ul>
      <ul class="navbar-nav">
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Help
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="{{ url_for('pages.view', slug='install-a-theme') }}">Install a Theme</a></li>
            <li><a class="dropdown-item" href="/pages/install-a-plugin">Install a Plugin</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="/pages/uploading-your-addon">Uploading Your Addon</a></li>
          </ul>
        </li>
        {% if logged_in_user %}
        {% if logged_in_user.is_moderator or logged_in_user.is_admin %}
        <li class="nav-item"><a href="{{ url_for('admin.index') }}" class="nav-link">Dashboard</a></li>
        {% endif %}
        <li class="nav-item"><a href="{{ url_for('user.logout') }}" class="nav-link">Log out</a></li>
        {% else %}
        <li class="nav-item"><a href="{{ url_for('user.login') }}" class="nav-link">Log in</a></li>
        {% endif %}
      </ul>
    </div>
  </div>
</nav>

<main class="{% block mainclasses %}container{% endblock %}">
{% block main %}{% endblock %}
</main>

<footer class="bg-secondary-subtle py-5 mt-5">
  <div class="container">
    <p class="float-end mb-1">
      <a href="#">Back to top</a>
    </p>
    <p class="mb-1">OpenLP Addons is a place for the OpenLP community to share plugins and themes that they have made.</p>
    <p class="mb-0">This platform is open source, you can download the <a href="https://gitlab.com/openlp/addons-repo">source code</a>.</p>
  </div>
</footer>
{% endblock layout %}

addonsrepo/templates/addons/themes.html
{% extends 'main/master.html' %}
{% block bodyclasses %}no-nav-padding{% endblock %}
{% block mainclasses %}bg-tertiary-subtle{% endblock %}
{% block main %}
  <section class="py-5 mb-5 text-bg-secondary page-themes">
    <div class="container">
      <h2>{{ page_title}} themes</h2>
    </div>
  </section>
  <div class="container">
    <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
      {% for addon in addons %}
      <div class="col">
        <div class="card shadow-sm">
          {% if addon.thumbnail_path %}
          <img src="{{ addon.thumbnail_path }}" class="card-img-top" alt="{{ addon.title }}">
          {% else %}
          <svg class="bd-placeholder-img card-img-top" width="100%" height="225" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: Thumbnail" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#55595c"/><text x="50%" y="50%" fill="#eceeef" dy=".3em">{{ addon.title }}</text></svg>
          {% endif %}
          <div class="card-body">
            <p class="card-text">{{ addon.description }}</p>
            <div class="d-flex justify-content-between align-items-center">
              <div class="btn-group">
                <button type="button" class="btn btn-sm btn-outline-secondary">View</button>
                <button type="button" class="btn btn-sm btn-outline-secondary">Edit</button>
              </div>
              <small class="text-body-secondary">9 mins</small>
            </div>
          </div>
        </div>
      </div>
      {% endfor %}
    </div>
  </div>
{% endblock main %}

addonsrepo/templates/addons/upload.html
{% extends 'addons/master.html' %}
{% block bodyclasses %}no-nav-padding{% endblock %}
{% block mainclasses %}bg-tertiary-subtle{% endblock %}
{% block extrascripts %}
<script src="{{ url_for('static', filename='js/forms.js') }}"></script>
{% endblock %}
{% block main %}
  <section class="py-5 mb-5 text-bg-secondary page-upload">
    <div class="container">
      <h2>Upload your {{ addon_type }}</h2>
    </div>
  </section>
  <div class="container">
    {% for category, message in get_flashed_messages(with_categories=True) %}
    <div class="alert alert-{{ category }} alert-dismissible fade show" role="alert">
      {{ message }}
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
    {% endfor %}
    <form action="{{ url_for('addons.upload_post', addon_type=addon_type) }}" method="post" enctype="multipart/form-data" novalidate>
      <div class="mb-3">
        <label for="title" class="form-label">Title</label>
        <input type="text" class="form-control" id="title" name="title" placeholder="My {{ addon_type }}" {% if session.get('title') %} value="{{ session.pop('title') }}"{% endif %}required>
        <div class="invalid-feedback">Please specify a title for your {{ addon_type }}</div>
        <p class="form-text">The title of your {{ addon_type }}</p>
      </div>
      <div class="mb-3">
        <label for="version" class="form-label">Version</label>
        <input type="text" class="form-control" id="version" name="version" placeholder="1.0" required>
        <div class="invalid-feedback">Please specify a version for your {{ addon_type }}</div>
        <p class="form-text">The version of your {{ addon_type }}</p>
      </div>
      <div class="mb-3">
        <label for="description" class="form-label">Description</label>
        <textarea class="form-control" id="description" name="description" rows="10" required></textarea>
        <div class="invalid-feedback">Please provide a description for your {{ addon_type }}</div>
        <p class="form-text">Plain text, no HTML or other formatting, links are removed</p>
      </div>
      <div class="mb-3">
        <label for="thumbnail" class="form-label">Thumbnail</label>
        <input type="file" class="form-control" id="thumbnail" name="thumbnail" accept="image/png, image/jpeg" required>
        <div class="invalid-feedback">Please provide a thumbnail for your {{ addon_type }}</div>
        <p class="form-text">A thumbnail, logo, or other descriptive image of your {{ addon_type }}</p>
      </div>
      <div class="mb-3">
        <label for="upload" class="form-label">{{ addon_type | title }} file</label>
        <input type="file" class="form-control" id="upload" name="upload" accept=".otz, application/zip" required>
        <div class="invalid-feedback">Please provide the file of your {{ addon_type }}</div>
        <p class="form-text">Upload your {{ addon_type }} here. See the <a href="{{ url_for('pages.view', slug='uploading-your-addon') }}">Uploading your addon</a> help page for more information</p>
      </div>
      {% if addon_type == 'theme' %}
      <div class="mb-3">
        <div class="form-check">
          <input type="checkbox" class="form-check-input" id="is_copyright_free" name="is_copyright_free" value="true" required>
          <label for="is_copyright_free" class="form-check-label">Free of copyrighted content</label>
        </div>
        <p class="form-text">Any images or other pieces of content in your theme need to be free of copyright</p>
      </div>
      {% elif addon_type == 'plugin' %}
      <div class="mb-3">
        <label for="license" class="form-label">License</label>
        <select class="form-select" id="license" name="license" required>
          <option value="GPL-3.0-or-later">GNU General Public License Version 3 or later (recommended)</option>
          <option value="LGPL-3.0-only">GNU Lesser General Public License version 3 (popular)</option>
          <option value="Apache-2.0">Apache License, Version 2.0</option>
          <option value="BSD-3-Clause">3-clause BSD License</option>
          <option value="MIT">MIT License</option>
          <option value="MPL-2.0">Mozilla Public License 2.0</option>
          <option value="Commercial">Unspecified commercial (non-open source) license (not recommended)</option>
        </select>
        <p class="form-text">The license of your {{ addon_type }}. See the <a href="{{ url_for('pages.view', slug='licenses') }}">Licenses</a> page for more information.</p>
      </div>
      {% endif %}
      <button type="submit" class="btn btn-primary">Upload</button>
    </form>
  </div>
{% endblock main %}